stages:
  - deploy

variables:
  PROJECT_DIR: /home/DOCKER_MCP_DATA

deploy:
  stage: deploy

  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'

  script:

    - mkdir -p $PROJECT_DIR

    - rsync -rvc --delete --exclude='.env' --exclude='.git' --exclude='builds/' ./ $PROJECT_DIR/

    - cd $PROJECT_DIR

    - docker compose down

    - docker compose build --no-cache

    - docker compose up -d --force-recreate

    - docker image prune -f

  tags:
    - q-ai-rig
